"""Add profile info

Revision ID: bfc734017100
Revises: 8e3cd6130ab0
Create Date: 2024-06-12 09:27:23.351235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc734017100'
down_revision = '8e3cd6130ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_request', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('support_request', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('support_request', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('support_request', sa.Column('office_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_request', 'full_name')
    op.drop_column('support_request', 'phone_number')
    op.drop_column('support_request', 'email')
    op.drop_column('support_request', 'office_number')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
